export const DISPLAY_QUESTIONS = 'DISPLAY_QUESTIONS';
export const CHOOSE_CATEGORY_STATUS ='CHOOSE_CATEGORY_STATUS';

export const FETCH_QUESTIONS_FULFILLED = 'FETCH_QUESTIONS_FULFILLED';
export const SET_CURRENT_QUESTION_COUNT = 'SET_CURRENT_QUESTION_COUNT';
export const GET_CURRENT_QUESTION = 'GET_CURRENT_QUESTION';

export const CORRECT_QUESTIONS_COUNT = 'CORRECT_QUESTIONS_COUNT';
export const SET_CORRECT_QUESTIONS_COUNT_ZERO = 'SET_CORRECT_QUESTIONS_COUNT_ZERO';

export const SHOW_END_SCORE = 'SHOW_END_SCORE'; 
